***************************************************************************
NOTE: LASE FON"T TRY TO RUN THIS MANUAL BECAUSE IT WAS NOT MEANT TO BE RUN!
***************************************************************************
Dear players of mystic adventure
We would like for you to write to us and see what you think. Our addres is
fred111782@aol.com

Intructions:
these are the tools we use in the game

get     go door     buy
open    read        attack monster
look at    n, e, s, w, ne, sw,
g, i, l, exp, quit, drink magic potion, and cast <spell name here> run
and ask jeremy to join me

If we left anything out, be sure and let us know!
This game is a lot like Zork tm.
WE WANT YOUR INFO!!!!!
WE WANT YOUR INFO!!!!!
WE WANT YOUR INFO!!!!!
WE WANT YOUR INFO!!!!!
WE WANT YOUR INFO!!!!!
WE WANT YOUR INFO!!!!!
WE WANT YOUR INFO!!!!!
WE WANT YOUR INFO!!!!!

Cam Smith $ Jon Henry

