'000   (nul)  016  (dle)  032 sp  048 0  064 @  080 P  096 `  112 p
'001  (soh)  017  (dc1)  033 !   049 1  065 A  081 Q  097 a  113 q
'002  (stx)  018  (dc2)  034 "   050 2  066 B  082 R  098 b  114 r
'003  (etx)  019  (dc3)  035 #   051 3  067 C  083 S  099 c  115 s
'004  (eot)  020  (dc4)  036 $   052 4  068 D  084 T  100 d  116 t
'005  (enq)  021  (nak)  037 %   053 5  069 E  085 U  101 e  117 u
'006  (ack)  022  (syn)  038 &   054 6  070 F  086 V  102 f  118 v
'007  (bel)  023  (etb)  039 '   055 7  071 G  087 W  103 g  119 w
'008  (bs)   024  (can)  040 (   056 8  072 H  088 X  104 h  120 x
'009   (tab)  025  (em)   041 )   057 9  073 I  089 Y  105 i  121 y
'010   (lf)   026   (eof)  042 *   058 :  074 J  090 Z  106 j  122 z
'011  (vt)   027  (esc)  043 +   059 ;  075 K  091 [  107 k  123 {
'012  (np)   028  (fs)   044 ,   060 <  076 L  092   108 l  124 |
'013   (cr)   029  (gs)   045 -   061 =  077 M  093 ]  109 m  125 }
'014  (so)   030  (rs)   046 .   062 >  078 N  094 ^  110 n  126 ~
'015  (si)   031  (us)   047 /   063 ?  079 O  095 _  111 o  127 

'128 Ä      144 ê      160 †    176 ∞    192 ¿    208 –    224 ‡   240 
'129 Å      145 ë      161 °    177 ±    193 ¡    209 —    225 ·   241 Ò
'130 Ç      146 í      162 ¢    178 ≤    194 ¬    210 “    226 ‚   242 Ú
'131 É      147 ì      163 £    179 ≥    195 √    211 ”    227 „   243 Û
'132 Ñ      148 î      164 §    180 ¥    196 ƒ    212 ‘    228 ‰   244 Ù
'133 Ö      149 ï      165 •    181 µ    197 ≈    213 ’    229 Â   245 ı
'134 Ü      150 ñ      166 ¶    182 ∂    198 ∆    214 ÷    230 Ê   246 ˆ
'135 á      151 ó      167 ß    183 ∑    199 «    215 ◊    231 Á   247 ˜
'136 à      152 ò      168 ®    184 ∏    200 »    216 ÿ    232 Ë   248 ¯
'137 â      153 ô      169 ©    185 π    201 …    217 Ÿ    233 È   249 ˘
'138 ä      154 ö      170 ™    186 ∫    202      218 ⁄    234 Í   250 ˙
'139 ã      155 õ      171 ´    187 ª    203 À    219 €    235 Î   251 ˚
'140 å      156 ú      172 ¨    188 º    204 Ã    220 ‹    236 Ï   252 ¸
'141 ç      157 ù      173 ≠    189 Ω    205 Õ    221 ›    237 Ì   253 ˝
'142 é      158 û      174 Æ    190 æ    206 Œ    222 ﬁ    238 Ó   254 ˛



'****************************************************************************
'*!           A Program Writen by: RvS Inc.                                !*
'*!                                                                        !*
'*!              RvS RPG Devision Presents:                                !*
'*!                                 The First True Astrology RPG           !*
'*!                                                                        !*
'*!                                                                        !*
'*!      TTTTTTTTTT   HHH  HHH EEEEEEEEE       AAA     GGGG   EEEEEEEEE    !*
'*!     TTTTTTTTTTTT  HHH  HHH EEEEEEEEE      AA AA   GG  GG  EEEEEEEEE    !*
'*!     T   TTTT   T  HHH  HHH EE            AA   AA GG    GG EE           !*
'*!         TTTT      HHHHHHHH EEEEE         AAAAAAA GG       EEEEE        !*
'*!         TTTT      HHH  HHH EE            AA   AA GG  GGGG EE           !*
'*!         TTTT      HHH  HHH EEEEEEEEE     AA   AA  GG  GGG EEEEEEEEE    !*
'*!         TTTT      HHH  HHH EEEEEEEEE     AA   AA   GGGG G EEEEEEEEE    !*
'*!                                                                        !*
'*!                                                                        !*
'*!                           OOOO     FFFFFFFFFF                          !*
'*!                          OO  OO    FFFFFFFFFF                          !*
'*!                         OO    OO   FFFF                                !*
'*!                         OO    OO   FFFFFFF                             !*
'*!                         OO    OO   FFFFFFF                             !*
'*!                          OO  OO    FFFF                                !*
'*!                           OOOO     FFFF                                !*
'*!                                                                        !*
'*!                                                                        !*
'*!    PPPPPPPP   IIIIIIIIIII   SSSSSS     CCCCCC  EEEEEEEEE   SSSSSS      !*
'*!    PP     PP  IIIIIIIIIII  SS    SS   CC    CC EE         SS    SS     !*
'*!    PP      PP     III     SS      SS CC      C EE        SS      SS    !*
'*!    PP      PP     III     SS         CC        EE        SS            !*
'*!    PP     PP      III      SS        CC        EE         SS           !*
'*!    PPPPPPPP       III       SSSSSS   CC        EEEEEE      SSSSSS      !*
'*!    PP             III            SS  CC        EE               SS     !*
'*!    PP             III             SS CC        EE                SS    !*
'*!    PP             III     SS      SS CC      C EE        SS      SS    !*
'*!    PP         IIIIIIIIIII  SS    SS   CC    CC EE         SS    SS     !*
'*!    PP         IIIIIIIIIII   SSSSSS     CCCCCC  EEEEEEEEE   SSSSSS      !*
'*!                                                                        !*
'****************************************************************************

CLS

SCREEN 8, , 1, 0
tp = 1: lf = 40: ri = 80: bt = 13
GOSUB border
tp = 1: lf = 1: ri = 80: bt = 25
GOSUB border
LOCATE 1, 40: PRINT CHR$(203);
LOCATE 13, 80: PRINT CHR$(185);
PCOPY 1, 0




DO WHILE INKEY$ = "": LOOP
END

border:
LOCATE tp, lf: PRINT CHR$(201);
LOCATE bt, lf: PRINT CHR$(200);
LOCATE tp, ri: PRINT CHR$(187);
LOCATE bt, ri: PRINT CHR$(188);
FOR a = (lf + 1) TO (ri - 1)
LOCATE tp, a: PRINT CHR$(205);
LOCATE bt, a: PRINT CHR$(205);
NEXT a
FOR a = (tp + 1) TO (bt - 1)
LOCATE a, ri: PRINT CHR$(186);
LOCATE a, lf: PRINT CHR$(186);
NEXT a
RETURN




